jobs:
  test:
    runs-on: ubuntu-latest
    environment: release
    name: Test
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"
          cache: "npm"
      - run: npm ci
      - run: npm run lint:eslint
      - run: npm run lint:tsc
      - run: npm run lint:cspell
      - run: npm run test:vitest
        env:
          ROARR_LOG: 'true'
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
name: Test, build and release
on:
  push:
    branches:
      - main